import Link from "next/link";
import Tech from "../Components/tech";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  console.log("what am i doing here --Server/Client");
  return (
    <>
      <h1 className="text-3xl">Welcome To Next.js</h1>
      <Tech />
      <li>
        <Link href="/about">Users</Link>
      </li>
      <li>
        <Link href="/products">Products</Link>
      </li>
    </>
  );
}
